//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemXem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activiti_import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activiti_import()
        {
            this.Events = new HashSet<Events>();
        }
    
        public int Id_activiti { get; set; }
        public Nullable<int> Столбец_2 { get; set; }
        public string Name_of_the_events { get; set; }
        public string Start_data { get; set; }
        public Nullable<byte> Day { get; set; }
        public string Activity { get; set; }
        public Nullable<byte> Day2 { get; set; }
        public Nullable<System.TimeSpan> Start_time { get; set; }
        public string Moderator { get; set; }
        public string Guri_1 { get; set; }
        public string Guri_2 { get; set; }
        public string Guri_3 { get; set; }
        public string Guri_4 { get; set; }
        public string Guri_5 { get; set; }
        public string Winner { get; set; }
        public string column16 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events> Events { get; set; }
    }
}
