//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemXem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int id_events { get; set; }
        public Nullable<int> Столбец_2 { get; set; }
        public string Events1 { get; set; }
        public string DATE { get; set; }
        public Nullable<byte> DAYS { get; set; }
        public Nullable<int> City { get; set; }
    
        public virtual Activiti_import Activiti_import { get; set; }
    }
}
