//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemXem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moderator
    {
        public int id_moderator { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Middle_name { get; set; }
        public Nullable<System.DateTime> Data_rogd { get; set; }
        public Nullable<int> Country { get; set; }
        public string Telephone { get; set; }
        public string Direction { get; set; }
        public string Events { get; set; }
        public string Password { get; set; }
        public string Phohto { get; set; }
    
        public virtual Country_import Country_import { get; set; }
        public virtual Country_import Country_import1 { get; set; }
    }
}
