//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemXem.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RulEntities : DbContext
    {
        private static RulEntities context;
        public RulEntities()
            : base("name=RulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static RulEntities GetContext()
        {
            if (context == null)
            {
                context = new RulEntities();
            }
            return context;
        }
    
        public virtual DbSet<Activiti_import> Activiti_import { get; set; }
        public virtual DbSet<Country_import> Country_import { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<guri> guri { get; set; }
        public virtual DbSet<Moderator> Moderator { get; set; }
        public virtual DbSet<organizator> organizator { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ychastnick> Ychastnick { get; set; }
    }
}
